galaxy_info:
  description: Instance Driver Linux
  author: Bojan Šernek
  min_ansible_version: "2.9"
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies:
  - role: instance_driver_common
