- name: Create or update systemd unit for instance driver
  ansible.builtin.template:
    src: instance_driver.service.j2
    dest: /etc/systemd/system/instance_driver.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart_instance_driver
