galaxy_info:
  description: Load Balancer
  author: Bojan Šernek
  min_ansible_version: "2.9"
  license: MIT
  platforms:
    - name: macOS
      versions:
        - all
dependencies:
  - role: "load_balancer_{{ ansible_os_family|lower }}"
