- name: Restart audio engine
  listen: restart_audio_engine
  become: true
  ansible.builtin.shell: |
    launchctl unload /Library/LaunchDaemons/io.audiocloud.audio_engine.plist 
    launchctl load -w /Library/LaunchDaemons/io.audiocloud.audio_engine.plist
