- name: Create or update launchd service plist
  ansible.builtin.template:
    src: io.audiocloud.instance_driver.plist.j2
    dest: /Library/LaunchDaemons/io.audiocloud.instance_driver.plist
    owner: root
    mode: 0644
  become: true
  notify: restart_instance_driver
