- name: generate launchd configuration
  ansible.builtin.template:
    src: io.audiocloud.domain_server.plist.j2
    dest: /Library/LaunchDaemons/io.audiocloud.domain_server.plist
  become: true
  notify: restart_domain_server
