galaxy_info:
  description: Instance Server
  author: Bojan Šernek
  min_ansible_version: "2.9"
  license: MIT
  platforms:
    - name: macOS
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
dependencies:
  - role: instance_driver_linux
    when: ansible_os_family == "Ubuntu" or ansible_os_family == "Debian"
  - role: instance_driver_darwin
    when: ansible_os_family == "Darwin"
