# Install NATS server with homebrew package manager.
- name: Install NATS server
  community.general.homebrew:
    name: nats-server
    state: present
  notify: restart_nats_server

# Ensure the NATS JetStream data directory exists. By default we keep up to 100 gigs on that directory.
- name: Ensure NATS data directory exists
  ansible.builtin.file:
    path: "{{ nats_server_data_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755
  notify: restart_nats_server

# Update the NATS server configuration startup script to read the config file. Default homebrew package does
# not use a configuration file, so we must create it.
- name: Create or update NATS server config file
  ansible.builtin.template:
    src: nats.conf.j2
    dest: "{{ nats_server_config_file }}"
    owner: "{{ ansible_user }}"
    mode: 0755
  notify: restart_nats_server

# Update the NATS server launchd file to read the config file. Default homebrew package does
# not use a configuration file, so we must update the launch configuration to use it.
- name: Update NATS server launchd file
  ansible.builtin.template:
    src: homebrew.mxcl.nats-server.plist.j2
    dest: "{{ nats_server_launchd_file }}"
    owner: "{{ ansible_user }}"
    mode: 0755
  notify: restart_nats_server
