galaxy_info:
  description: NATS Server
  author: Bojan Šernek
  min_ansible_version: "2.9"
  license: MIT
  platforms:
    - name: macOS
      versions:
        - all
dependencies:
  - role: nats_server_darwin
    when: ansible_os_family == "Darwin"
