- name: Create audiocloud directory
  ansible.builtin.file:
    path: "{{ instance_driver_path }}"
    state: directory
    mode: 0755
    recurse: true
    owner: "{{ ansible_user }}"
  become: true
- name: Stat audiocloud directory
  ansible.builtin.stat:
    path: "{{ instance_driver_path }}"
  register: instance_driver_path_stat
- name: Import file download tasks for UNIX platforms
  ansible.builtin.import_tasks: download_unix.yml
  when: ansible_os_family != "Windows"
- name: Import Linux tasks
  ansible.builtin.import_tasks: linux.yml
  when: ansible_os_family == "Linux"
- name: Import macOS tasks
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"
