- name: Create audiocloud directory
  ansible.builtin.file:
    path: "{{ instance_driver_path }}"
    state: directory
    mode: 0755
    recurse: yes
    owner: "{{ ansible_user }}"
  become: true
- name: Stat audiocloud directory
  ansible.builtin.stat:
    path: "{{ instance_driver_path }}"
  register: instance_driver_path_stat
- import_tasks: download_unix.yml
  when: ansible_os_family != "Windows"
- import_tasks: linux.yml
  when: ansible_os_family == "Linux"
- import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"
