- name: Restart instance driver with systemctl
  ansible.builtin.systemd:
    name: audiocloud_instance_driver
    state: restarted
    daemon_reload: yes
  become: true
  listen: restart_instance_driver
