- name: Restart instance driver
  listen: restart_instance_driver
  become: true
  ansible.builtin.shell: |
    launchctl unload /Library/LaunchDaemons/io.audiocloud.instance_driver.plist
    launchctl load -w /Library/LaunchDaemons/io.audiocloud.instance_driver.plist
