# We are OK with stop failing, because on first boot it does not exist yet
- name: Restart domain server
  listen: restart_domain_server
  become: true
  ansible.builtin.shell: |
    launchctl unload /Library/LaunchDaemons/io.audiocloud.domain_server.plist
    launchctl load -w /Library/LaunchDaemons/io.audiocloud.domain_server.plist
