# We are OK with stop failing, because on first boot it does not exist yet
- name: Restart domain server
  listen: restart_domain_server
  become: true
  ansible.builtin.shell: |
    launchctl stop io.audiocloud.domain_server
    launchctl start io.audiocloud.domain_server
