on:
  push: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ansible Lint
        run: |
          pip install ansible-lint
      - name: Run Ansible Lint
        run: |
          ansible-lint
